---
title: "lucas_cleaning"
output: html_document
---

```{r loading packages}
suppressWarnings(suppressPackageStartupMessages(library(tidyverse)))
suppressWarnings(suppressPackageStartupMessages(library(GLDreg)))
```

```{r copy of dataset}
edit_actg <- actg
```

```{r cleaning datatset}
edit_actg <- 
  edit_actg |> 
  mutate(
    txgrp = factor(txgrp, levels = 1:4, labels = c('zdv', 'idv_zdv', 'd4t', 'idv_d4t')), #3TC is included in all trt groups, so redundant in labels
    cd4_lvl = factor(strat2, levels = 0:1, labels = c('<=50', '>50')),
    sex = factor(sex, levels = 0:1, labels = c('male', 'female')),
    race = factor(raceth, levels = 1:6, labels = c('wnh', 'bnh', 'h', 'api', 'ai', 'other')),
    ivdrug = factor(ivdrug, levels = 1:3, labels = c('never', 'currently', 'previously')),
    event = censor,
    time_event = time,
    death = censor_d,
    time_death = time_d,
    base_cd4 = cd4
  ) |> 
  select(-c(raceth, strat2, time, time_d, censor, censor_d, cd4))
```

```{r adding to data folder}
saveRDS(edit_actg, '../data/actg_clean.rds')
```